#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : latte-dock
Version  : 0.9.2
Release  : 7
URL      : https://github.com/KDE/latte-dock/archive/v0.9.2/latte-dock-0.9.2.tar.gz
Source0  : https://github.com/KDE/latte-dock/archive/v0.9.2/latte-dock-0.9.2.tar.gz
Summary  : A dock based on Plasma Frameworks
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: latte-dock-bin = %{version}-%{release}
Requires: latte-dock-data = %{version}-%{release}
Requires: latte-dock-lib = %{version}-%{release}
Requires: latte-dock-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules pkgconfig(xcb) xcb-util-cursor-dev xcb-util-image-dev xcb-util-keysyms-dev xcb-util-renderutil-dev xcb-util-wm-dev xcb-util-dev
BuildRequires : kactivities-dev
BuildRequires : kglobalaccel-dev
BuildRequires : kwayland-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : libksysguard-dev
BuildRequires : plasma-framework-dev
BuildRequires : qtbase-dev mesa-dev

%description
About
=====
Latte is a dock based on plasma frameworks that provides an elegant and intuitive experience for your tasks and plasmoids. It animates its contents by using parabolic zoom effect and trys to be there only when it is needed.

%package bin
Summary: bin components for the latte-dock package.
Group: Binaries
Requires: latte-dock-data = %{version}-%{release}
Requires: latte-dock-license = %{version}-%{release}

%description bin
bin components for the latte-dock package.


%package data
Summary: data components for the latte-dock package.
Group: Data

%description data
data components for the latte-dock package.


%package lib
Summary: lib components for the latte-dock package.
Group: Libraries
Requires: latte-dock-data = %{version}-%{release}
Requires: latte-dock-license = %{version}-%{release}

%description lib
lib components for the latte-dock package.


%package license
Summary: license components for the latte-dock package.
Group: Default

%description license
license components for the latte-dock package.


%prep
%setup -q -n latte-dock-0.9.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567713809
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1567713809
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/latte-dock
cp COPYING %{buildroot}/usr/share/package-licenses/latte-dock/COPYING
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/latte-dock/COPYING.LIB
cp containment/package/contents/icons/COPYING %{buildroot}/usr/share/package-licenses/latte-dock/containment_package_contents_icons_COPYING
cp icons/COPYING %{buildroot}/usr/share/package-licenses/latte-dock/icons_COPYING
cp shell/package/contents/images/COPYING %{buildroot}/usr/share/package-licenses/latte-dock/shell_package_contents_images_COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/latte-dock

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.latte-dock.desktop
/usr/share/dbus-1/interfaces/org.kde.LatteDock.xml
/usr/share/icons/breeze/applets/256/org.kde.latte.plasmoid.svg
/usr/share/icons/hicolor/16x16/apps/latte-dock.svg
/usr/share/icons/hicolor/22x22/apps/latte-dock.svg
/usr/share/icons/hicolor/24x24/apps/latte-dock.svg
/usr/share/icons/hicolor/32x32/apps/latte-dock.svg
/usr/share/icons/hicolor/48x48/apps/latte-dock.svg
/usr/share/icons/hicolor/scalable/apps/latte-dock.svg
/usr/share/knotifications5/lattedock.notifyrc
/usr/share/kservices5/plasma-applet-org.kde.latte.containment.desktop
/usr/share/kservices5/plasma-applet-org.kde.latte.plasmoid.desktop
/usr/share/kservices5/plasma-containmentactions-lattecontextmenu.desktop
/usr/share/kservices5/plasma-shell-org.kde.latte.shell.desktop
/usr/share/kservicetypes5/latte-indicator.desktop
/usr/share/latte/indicators/default/metadata.desktop
/usr/share/latte/indicators/default/package/config/config.qml
/usr/share/latte/indicators/default/package/config/main.xml
/usr/share/latte/indicators/default/package/ui/main.qml
/usr/share/latte/indicators/org.kde.latte.plasma/metadata.desktop
/usr/share/latte/indicators/org.kde.latte.plasma/package/config/config.qml
/usr/share/latte/indicators/org.kde.latte.plasma/package/config/main.xml
/usr/share/latte/indicators/org.kde.latte.plasma/package/ui/BackLayer.qml
/usr/share/latte/indicators/org.kde.latte.plasma/package/ui/FrontLayer.qml
/usr/share/latte/indicators/org.kde.latte.plasma/package/ui/main.qml
/usr/share/metainfo/org.kde.latte-dock.appdata.xml
/usr/share/metainfo/org.kde.latte.plasmoid.appdata.xml
/usr/share/metainfo/org.kde.latte.shell.appdata.xml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code/AppletIdentifier.js
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code/ColorizerTools.js
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code/HeuristicTools.js
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code/LayoutManager.js
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/code/MathTools.js
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/AUTHORS
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/COPYING
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/blueprint.jpg
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/brownprint.jpg
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/darkgreyprint.jpg
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/goldprint.jpg
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/greenprint.jpg
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/lightskyblueprint.jpg
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/orangeprint.jpg
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/pinkprint.jpg
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/purpleprint.jpg
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/redprint.jpg
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/icons/wheatprint.jpg
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/DebugWindow.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/DragDropArea.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/PanelBox.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/ParabolicManager.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/RootMouseArea.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/VisibilityManager.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/AppletItem.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/HiddenSpacer.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/ItemWrapper.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/ShortcutBadge.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/TitleTooltipParent.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/colorizer/Applet.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/communicator/Actions.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/communicator/Engine.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/communicator/LatteBridge.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/indicator/Bridge.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/indicator/LevelOptions.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/applet/indicator/Loader.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/colorizer/CustomBackground.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/colorizer/Manager.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/editmode/ConfigOverlay.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/editmode/HeaderSettings.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/editmode/SettingsOverlay.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/editmode/Visual.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/editmode/controls/Button.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/editmode/controls/RearrangeIcon.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/editmode/maxlength/Ruler.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/editmode/maxlength/RulerMouseArea.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/indicators/Manager.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/layouts/AppletsContainer.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/layouts/EnvironmentActions.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/layouts/LayoutsContainer.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/layouts/loaders/Tasks.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.latte.containment/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.latte.containment/metadata.json
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/ColorizerTools.js
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/activitiesTools.js
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/layout.js
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/code/tools.js
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/images/panel-west.png
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ContextMenu.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/ParabolicManager.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/PulseAudio.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/TasksExtendedManager.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/config/ConfigAppearance.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/config/ConfigInteraction.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/config/ConfigPanel.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/indicators/Manager.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/indicators/options/Latte.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/indicators/styles/LatteIndicator.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/previews/ToolTipDelegate2.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/previews/ToolTipInstance.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/previews/ToolTipWindowMouseArea.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/AudioStream.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/HiddenSpacer.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/IconItem.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/ProgressOverlay.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/ShortcutBadge.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/SubWindows.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/TaskItem.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/TitleTooltipParent.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/Wrapper.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/animations/ClickedAnimation.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/animations/FastRestoreAnimation.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/animations/LauncherAnimation.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/animations/NewWindowAnimation.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/animations/RealRemovalAnimation.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/animations/RemoveWindowFromGroupAnimation.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/animations/RestoreAnimation.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/animations/ShowWindowAnimation.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/indicator/Bridge.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/indicator/LevelOptions.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/task/indicator/Loader.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/taskslayout/MouseHandler.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/taskslayout/ScrollEdgeShadows.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/taskslayout/ScrollOpacityMask.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/taskslayout/ScrollPositioner.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/contents/ui/taskslayout/ScrollableList.qml
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.latte.plasmoid/metadata.json
/usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteDockConfiguration.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/LatteDockSecondaryConfiguration.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/config.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/pages/AppearanceConfig.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/pages/BehaviorConfig.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/pages/EffectsConfig.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/configuration/pages/TasksConfig.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/controls/CustomIndicatorButton.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/controls/InnerShadow.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/controls/TypeSelection.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/defaults
/usr/share/plasma/shells/org.kde.latte.shell/contents/images/AUTHORS
/usr/share/plasma/shells/org.kde.latte.shell/contents/images/COPYING
/usr/share/plasma/shells/org.kde.latte.shell/contents/images/splitter.svgz
/usr/share/plasma/shells/org.kde.latte.shell/contents/images/trademark.svgz
/usr/share/plasma/shells/org.kde.latte.shell/contents/layouts/Default.latterc
/usr/share/plasma/shells/org.kde.latte.shell/contents/layouts/Extended.latterc
/usr/share/plasma/shells/org.kde.latte.shell/contents/layouts/Plasma.latterc
/usr/share/plasma/shells/org.kde.latte.shell/contents/layouts/Unity.latterc
/usr/share/plasma/shells/org.kde.latte.shell/contents/presets/Default.layout.latte
/usr/share/plasma/shells/org.kde.latte.shell/contents/presets/Extended.layout.latte
/usr/share/plasma/shells/org.kde.latte.shell/contents/presets/Plasma.layout.latte
/usr/share/plasma/shells/org.kde.latte.shell/contents/presets/Unity.layout.latte
/usr/share/plasma/shells/org.kde.latte.shell/contents/presets/multiple-layouts_hidden.layout.latte
/usr/share/plasma/shells/org.kde.latte.shell/contents/scripting/BackgroundTracer.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/views/InfoView.qml
/usr/share/plasma/shells/org.kde.latte.shell/contents/views/Panel.qml
/usr/share/plasma/shells/org.kde.latte.shell/metadata.desktop
/usr/share/plasma/shells/org.kde.latte.shell/metadata.json
/usr/share/xdg/latte-indicators.knsrc
/usr/share/xdg/latte-layouts.knsrc

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kpackage/packagestructure/latte_packagestructure_indicator.so
/usr/lib64/qt5/plugins/plasma_containmentactions_lattecontextmenu.so
/usr/lib64/qt5/qml/org/kde/latte/components/AddItem.qml
/usr/lib64/qt5/qml/org/kde/latte/components/AddingArea.qml
/usr/lib64/qt5/qml/org/kde/latte/components/BadgeText.qml
/usr/lib64/qt5/qml/org/kde/latte/components/CheckBox.qml
/usr/lib64/qt5/qml/org/kde/latte/components/CheckBoxesColumn.qml
/usr/lib64/qt5/qml/org/kde/latte/components/ComboBox.qml
/usr/lib64/qt5/qml/org/kde/latte/components/ComboBoxButton.qml
/usr/lib64/qt5/qml/org/kde/latte/components/ExternalShadow.qml
/usr/lib64/qt5/qml/org/kde/latte/components/GlowPoint.qml
/usr/lib64/qt5/qml/org/kde/latte/components/Header.qml
/usr/lib64/qt5/qml/org/kde/latte/components/HeaderSwitch.qml
/usr/lib64/qt5/qml/org/kde/latte/components/IndicatorItem.qml
/usr/lib64/qt5/qml/org/kde/latte/components/ItemDelegate.qml
/usr/lib64/qt5/qml/org/kde/latte/components/Label.qml
/usr/lib64/qt5/qml/org/kde/latte/components/Slider.qml
/usr/lib64/qt5/qml/org/kde/latte/components/SpinBox.qml
/usr/lib64/qt5/qml/org/kde/latte/components/SubHeader.qml
/usr/lib64/qt5/qml/org/kde/latte/components/Switch.qml
/usr/lib64/qt5/qml/org/kde/latte/components/TextField.qml
/usr/lib64/qt5/qml/org/kde/latte/components/ToolTip.qml
/usr/lib64/qt5/qml/org/kde/latte/components/code/ColorizerTools.js
/usr/lib64/qt5/qml/org/kde/latte/components/private/ButtonShadow.qml
/usr/lib64/qt5/qml/org/kde/latte/components/private/CheckBoxStyle.qml
/usr/lib64/qt5/qml/org/kde/latte/components/private/DefaultListItemBackground.qml
/usr/lib64/qt5/qml/org/kde/latte/components/private/MobileCursor.qml
/usr/lib64/qt5/qml/org/kde/latte/components/private/MobileTextActionsToolBar.qml
/usr/lib64/qt5/qml/org/kde/latte/components/private/RoundShadow.qml
/usr/lib64/qt5/qml/org/kde/latte/components/private/SwitchStyle.qml
/usr/lib64/qt5/qml/org/kde/latte/components/private/TextFieldFocus.qml
/usr/lib64/qt5/qml/org/kde/latte/components/qmldir
/usr/lib64/qt5/qml/org/kde/latte/liblatte2plugin.so
/usr/lib64/qt5/qml/org/kde/latte/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/latte-dock/COPYING
/usr/share/package-licenses/latte-dock/COPYING.LIB
/usr/share/package-licenses/latte-dock/containment_package_contents_icons_COPYING
/usr/share/package-licenses/latte-dock/icons_COPYING
/usr/share/package-licenses/latte-dock/shell_package_contents_images_COPYING
